services:
  database:
    image: postgres:17.4-alpine
    container_name: uff-database
    platform: linux/x86_64
    environment:
      POSTGRES_USER: 'uff'
      POSTGRES_DB: 'uffdb'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: '/data/postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db:/data/postgres

  uff-main:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: uff-main
    env_file:
      - .env.development
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/pnpm/store

volumes:
  db:
  pnpm-store: