services:
  database:
    image: postgres:17.4-alpine
    container_name: uff-database
    environment:
      POSTGRES_USER: 'uff'
      POSTGRES_DB: 'uffdb'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: '/data/postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
    - db:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uff -d uffdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  main:
    build: .
    tty: true
    container_name: uff-main
    env_file:
      - .env.development
    ports:
      - '3000:3000'
      - '9229:9229'
      - '4000:4000'
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/pnpm/store

volumes:
  db:
  pnpm-store: