services:
  main:
    build: .
    container_name: uff
    tty: true
    ports:
      - '3000:3000'
      - '4200:4200'
    volumes:
      - .:/src/app
    environment:
      DATABASE_URL: 'postgresql://uff:Sup3rSecre!P4ssw0rd@postgres:5432/uffdb?schema=public'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: 'uff'
      POSTGRES_PASSWORD: 'Sup3rSecre!P4ssw0rd'
      POSTGRES_DB: 'uffdb'
      PGDATA: '/data/postgres'
    restart: always
    volumes:
      - db:/data/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  db:
