services:
  database:
    image: postgres:17.4-alpine
    container_name: uff-database
    platform: linux/x86_64
    environment:
      POSTGRES_USER: 'uff'
      POSTGRES_DB: 'uffdb'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      PGDATA: '/data/postgres'
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - db:/data/postgres

  uff-api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: uff-api
    env_file:
      - .env.development
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/pnpm/store

  uff:
    build:
      context: .
      dockerfile: apps/uff/Dockerfile
    container_name: uff
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - api
    restart: unless-stopped
    volumes:
      - ./apps/uff:/usr/src/app/apps/uff
      - ./libs:/usr/src/app/libs
      - /usr/src/app/node_modules
      - /usr/src/app/apps/uff/node_modules

volumes:
  db:
  pnpm-store: