services:
  main:
    build: .
    container_name: uff
    tty: true
    ports:
      - '3000:3000'
      - '4200:4200'
    volumes:
      - .:/src/app

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  mysql:
    environment:
      MYSQL_DATABASE: 'uff'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    expose:
      - '3306'
    image: mysql:9.0.1
    platform: linux/x86_64 # sorry, my fellow arm user
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - uffdb:/var/lib/mysql

volumes:
  uffdb:
