import { Toaster } from '@/uff-ui';
import './global.css';

export const metadata = {
  title: 'Welcome to uff',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
