<<<<<<< HEAD:apps/uff/src/app/layout.tsx
import Providers from '../components/providers';
=======
import { Toaster } from '@/uff-ui';
>>>>>>> origin/master:apps/web/src/app/layout.tsx
import './global.css';

export const metadata = {
  title: 'Welcome to uff',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
