FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ENV NX_DAEMON="false"
ENV NX_WORKSPACE_ROOT="/app"

RUN corepack enable \
 && apt-get update -y \
 && apt-get install -y openssl procps curl

WORKDIR /app
RUN pnpm config set store-dir /pnpm/store

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

COPY . .
