import Providers from '../components/providers';
import { Toaster } from '@uff/ui/sonner';
import './global.css';

export const metadata = {
  title: 'Welcome to uff',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>
          {children}
          <Toaster richColors />
        </body>
      </Providers>
    </html>
  );
}
